// Complete pet data for HAP's Animal Placement
// - Full data fields for the site
// - Prompt field for image generation
// - Description field with shelter-style personality text

export const pets = [
  // === CATS (9) ===
  {
    id: "a3f8c1",
    name: "Whisker",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "affectionate",
    status: "available",
    prompt: "fluffy orange tabby cat with green eyes",
    description: "A classic tabby who lives for chin scratches and sunny windowsills. Will greet you at the door every single day without fail.",
  },
  {
    id: "b7e2d4",
    name: "Marmalade",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "playful marmalade cat batting at a toy",
    description: "This orange goofball has two speeds: zooming and napping. Favorite toy: anything that crinkles. Will make you laugh daily.",
  },
  {
    id: "c9a1f6",
    name: "Shadow",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "independent",
    status: "available",
    prompt: "sleek black cat with golden eyes sitting elegantly",
    description: "A mysterious soul who enjoys quiet companionship. Will sit near you, not on you. Perfect for someone who respects boundaries.",
  },
  {
    id: "d2c5b8",
    name: "Snowball",
    species: "cat",
    subcategory: "kitten",
    specialNeeds: null,
    temperament: "playful",
    status: "pending",
    prompt: "tiny white kitten with blue eyes and pink nose",
    description: "Tiny but mighty! This curious kitten is learning the ropes and ready for adventure. Needs patient adopter for kitten antics.",
  },
  {
    id: "e6f3a2",
    name: "Mittens",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "fluffy gray and white tuxedo cat",
    description: "A laid-back sweetheart who gets along with everyone. Perfect for first-time cat owners. Low drama, high purrs.",
  },
  {
    id: "f1d8e7",
    name: "Tripod",
    species: "cat",
    subcategory: "adult",
    specialNeeds: "amputee",
    temperament: "affectionate",
    status: "available",
    prompt: "brave orange cat with three legs hopping happily",
    description: "Lost a leg but not his spirit. This brave boy purrs louder than any cat we know. Doesn't know he's different, just knows he's loved.",
  },
  {
    id: "a8b4c3",
    name: "Sugar",
    species: "cat",
    subcategory: "senior",
    specialNeeds: "senior",
    temperament: "calm",
    status: "available",
    prompt: "wise senior gray cat with white whiskers and gentle eyes",
    description: "A gentle senior who just wants a warm lap and a peaceful home. Low maintenance, high love. Already litter trained and drama-free.",
  },
  {
    id: "b3e9f5",
    name: "Byte",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "independent",
    status: "adopted",
    prompt: "clever gray tabby cat with stripes",
    description: "HAP's first cat! Loves keyboards and will 'help' you code. Now living his best life with his forever family.",
  },
  {
    id: "c4a7d1",
    name: "Cache",
    species: "cat",
    subcategory: "adult",
    specialNeeds: null,
    temperament: "affectionate",
    status: "adopted",
    prompt: "beautiful calico cat with patches of orange black and white",
    description: "HAP's second cat! Named for her ability to hide treats everywhere. Expert napper, professional cuddler.",
  },

  // === DOGS (12) ===
  {
    id: "d9f2b6",
    name: "Buddy",
    species: "dog",
    subcategory: "large",
    specialNeeds: null,
    temperament: "playful",
    status: "adopted",
    prompt: "happy golden retriever with tongue out and wagging tail",
    description: "The ultimate family dog. Loved kids, fetch, and belly rubs in equal measure. Found his forever home and couldn't be happier!",
  },
  {
    id: "e1c8a4",
    name: "Luna",
    species: "dog",
    subcategory: "large",
    specialNeeds: null,
    temperament: "energetic",
    status: "available",
    prompt: "athletic black labrador ready to run",
    description: "High-energy lab who needs lots of exercise. Perfect running partner or hiking buddy. Will keep you active!",
  },
  {
    id: "f5d3e9",
    name: "Max",
    species: "dog",
    subcategory: "medium",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "curious beagle with floppy ears sniffing the air",
    description: "A curious beagle with an impressive nose. Loves sniffing out treats and going on walks. Food motivated, easy to train.",
  },
  {
    id: "a2b7c8",
    name: "Bella",
    species: "dog",
    subcategory: "large",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "noble german shepherd standing alert",
    description: "A well-trained shepherd looking for a job to do. Smart, loyal, and protective. Best with experienced dog owner.",
  },
  {
    id: "b8c1d5",
    name: "Charlie",
    species: "dog",
    subcategory: "medium",
    specialNeeds: null,
    temperament: "energetic",
    status: "available",
    prompt: "smart border collie with bright eyes",
    description: "Smartest dog in the shelter! Knows 15 tricks and ready to learn more. Needs mental stimulation and an active family.",
  },
  {
    id: "c3e6f2",
    name: "Daisy",
    species: "dog",
    subcategory: "medium",
    specialNeeds: null,
    temperament: "affectionate",
    status: "available",
    prompt: "sweet cocker spaniel with long wavy ears",
    description: "Total cuddle bug who thinks she's a lap dog. Velcro pup alert! Will follow you from room to room.",
  },
  {
    id: "d7a4b1",
    name: "Rocky",
    species: "dog",
    subcategory: "medium",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "chunky english bulldog with a wrinkly face",
    description: "A chill bulldog who snores louder than he barks. Loves short walks and long naps. Perfect apartment companion.",
  },
  {
    id: "e9f8c6",
    name: "Coco",
    species: "dog",
    subcategory: "small",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "fluffy white poodle with a cute haircut",
    description: "Hypoallergenic poodle with a playful personality. Great for apartments and allergy sufferers. Smart and easy to train.",
  },
  {
    id: "f2d1a7",
    name: "Milo",
    species: "dog",
    subcategory: "small",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "tiny chihuahua with big ears and bigger eyes",
    description: "A tiny chi with a big heart. Takes time to warm up but bonds deeply. Needs patient adopter, no small children please.",
  },
  {
    id: "a6c3e4",
    name: "Ziggy",
    species: "dog",
    subcategory: "small",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "long dachshund with short legs and floppy ears",
    description: "Long and low, this wiener dog thinks he's huge. Surprisingly fast! Loves burrowing under blankets.",
  },
  {
    id: "b1f5d8",
    name: "Echo",
    species: "dog",
    subcategory: "large",
    specialNeeds: "blind",
    temperament: "calm",
    status: "available",
    prompt: "gentle husky with pale blue cloudy eyes",
    description: "Blind but brave. Navigates by sound and has the sweetest howl. Adapts quickly to new spaces once he learns the layout.",
  },
  {
    id: "c8a2f9",
    name: "Hopper",
    species: "dog",
    subcategory: "small",
    specialNeeds: "amputee",
    temperament: "energetic",
    status: "available",
    prompt: "spunky terrier mix hopping on three legs",
    description: "Three legs, zero limits. This terrier mix has more energy than dogs with four. Don't let the missing leg fool you!",
  },

  // === SMALL MAMMALS (8) ===
  {
    id: "d4e7b3",
    name: "Nugget",
    species: "small mammal",
    subcategory: "hamster",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "chubby golden hamster with stuffed cheeks",
    description: "A fluffy golden hamster who runs on his wheel all night. Peak entertainment value. Great starter pet for older kids.",
  },
  {
    id: "e2c9a1",
    name: "Peanut",
    species: "small mammal",
    subcategory: "hamster",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "tiny dwarf hamster curled in a ball",
    description: "Tiny dwarf hamster who fits in your palm. Shy at first, then super curious. Nocturnal, so perfect for night owls.",
  },
  {
    id: "f6b8d4",
    name: "Patches",
    species: "small mammal",
    subcategory: "guinea pig",
    specialNeeds: null,
    temperament: "affectionate",
    status: "available",
    prompt: "fluffy calico guinea pig with swirly fur",
    description: "Social guinea pig who squeaks when she hears the fridge open. Veggie lover. Does best with a guinea pig friend!",
  },
  {
    id: "a9d2c7",
    name: "Cinnamon",
    species: "small mammal",
    subcategory: "guinea pig",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "round brown guinea pig munching on hay",
    description: "The calm one of the pair. Loves lap time and gentle pets. Would love to be adopted with Patches!",
  },
  {
    id: "b5a1e6",
    name: "Thumper",
    species: "small mammal",
    subcategory: "rabbit",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "soft gray rabbit with twitching nose",
    description: "A playful rabbit who binkies when he's happy. Watch out for zoomies! Litter trained and full of personality.",
  },
  {
    id: "c1f4d2",
    name: "Cotton",
    species: "small mammal",
    subcategory: "rabbit",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "fluffy white rabbit with pink ears",
    description: "A shy white rabbit who needs patience. Once she trusts you, she's a total lovebug. Worth the wait!",
  },
  {
    id: "d8e3b9",
    name: "Ginger",
    species: "small mammal",
    subcategory: "ferret",
    specialNeeds: null,
    temperament: "energetic",
    status: "available",
    prompt: "sleek ferret stretching playfully",
    description: "Mischievous ferret who steals socks. Endless entertainment guaranteed. Ferret-proof your home first!",
  },
  {
    id: "e4a6c1",
    name: "Nibbles",
    species: "small mammal",
    subcategory: "chinchilla",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "round gray chinchilla with big ears",
    description: "Soft chinchilla who gives dust baths like it's a spa day. Nocturnal and needs cool temperatures.",
  },

  // === BIRDS (6) ===
  {
    id: "f3c7d8",
    name: "Kiwi",
    species: "bird",
    subcategory: "parakeet",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "bright green parakeet tilting head curiously",
    description: "Chatty green parakeet learning to say 'hello.' Loves mirrors and bells. Great first bird!",
  },
  {
    id: "a1e4b5",
    name: "Sunny",
    species: "bird",
    subcategory: "parakeet",
    specialNeeds: null,
    temperament: "affectionate",
    status: "available",
    prompt: "cheerful yellow parakeet singing",
    description: "This yellow parakeet will sit on your shoulder all day. Total companion bird. Loves to sing along to music.",
  },
  {
    id: "b6d9a3",
    name: "Mango",
    species: "bird",
    subcategory: "cockatiel",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "gray cockatiel with orange cheek patches and crest up",
    description: "Whistling cockatiel who does a great doorbell impression. Very social, loves head scratches.",
  },
  {
    id: "c2f1e8",
    name: "Rio",
    species: "bird",
    subcategory: "parakeet",
    specialNeeds: null,
    temperament: "energetic",
    status: "available",
    prompt: "vibrant blue parakeet with wings spread",
    description: "Vibrant blue parakeet with serious attitude. Small bird, big personality. Needs room to fly!",
  },
  {
    id: "d5b2c4",
    name: "Peaches",
    species: "bird",
    subcategory: "lovebird",
    specialNeeds: null,
    temperament: "affectionate",
    status: "available",
    prompt: "peach-faced lovebird with bright colors",
    description: "A lovebird who lives up to the name. Needs lots of attention and gives it back tenfold. Velcro bird!",
  },
  {
    id: "e8a9f7",
    name: "Phoenix",
    species: "bird",
    subcategory: "cockatiel",
    specialNeeds: "rescue",
    temperament: "shy",
    status: "available",
    prompt: "gentle cockatiel with ruffled feathers looking hopeful",
    description: "Rescue cockatiel still growing back feathers. Gentle soul who's been through a lot. Needs patient, quiet home.",
  },

  // === REPTILES (6) ===
  {
    id: "f4c2d6",
    name: "Spike",
    species: "reptile",
    subcategory: "lizard",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "friendly bearded dragon basking with eyes half closed",
    description: "Friendly bearded dragon who loves basking and the occasional blueberry. Surprisingly personable for a reptile!",
  },
  {
    id: "a7e8b1",
    name: "Scales",
    species: "reptile",
    subcategory: "lizard",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "spotted leopard gecko with big eyes",
    description: "Shy leopard gecko who comes out at dusk. Beautiful spotted pattern. Low maintenance, great for beginners.",
  },
  {
    id: "b2d4c9",
    name: "Pretzel",
    species: "reptile",
    subcategory: "snake",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "coiled ball python with pretty brown patterns",
    description: "Docile ball python who curls up in the cutest shapes. Great for first-time snake owners. Eats frozen/thawed.",
  },
  {
    id: "c6a3e5",
    name: "Shelly",
    species: "reptile",
    subcategory: "turtle",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "red-eared slider turtle peeking out of shell",
    description: "Red-eared slider who loves her basking spot. Watching her swim is so calming. Long-term commitment pet!",
  },
  {
    id: "d1f7b4",
    name: "Rex",
    species: "reptile",
    subcategory: "lizard",
    specialNeeds: null,
    temperament: "independent",
    status: "available",
    prompt: "blue-tongued skink showing off blue tongue",
    description: "Blue-tongued skink with a funny defensive pose. Actually a big softy once comfortable. Loves snails!",
  },
  {
    id: "e3c5a8",
    name: "Mossy",
    species: "reptile",
    subcategory: "lizard",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "adorable crested gecko with eyelash-like ridges",
    description: "Crested gecko with adorable eyelash ridges. Nocturnal and low-maintenance. Doesn't need live bugs!",
  },

  // === AQUATIC (7) ===
  {
    id: "f9b6d3",
    name: "Bubbles",
    species: "aquatic",
    subcategory: "fish",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "plump orange goldfish with flowing fins",
    description: "Classic goldfish who's been here the longest. Simple but soothing. Needs proper tank, not a bowl!",
  },
  {
    id: "a4d1e2",
    name: "Nemo",
    species: "aquatic",
    subcategory: "fish",
    specialNeeds: null,
    temperament: "playful",
    status: "available",
    prompt: "bright orange clownfish with white stripes",
    description: "Clownfish with major personality. Darts around his anemone all day. Saltwater setup required.",
  },
  {
    id: "b9c8f4",
    name: "Pearl",
    species: "aquatic",
    subcategory: "fish",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "elegant white betta fish with flowing fins",
    description: "Elegant white betta with flowing fins like a wedding dress. Prefers peaceful tank, solo only.",
  },
  {
    id: "c5e2a6",
    name: "Coral",
    species: "aquatic",
    subcategory: "fish",
    specialNeeds: null,
    temperament: "independent",
    status: "available",
    prompt: "fierce red betta fish with dramatic fins",
    description: "Feisty red betta who flares at her own reflection. Dramatic and beautiful. Solo tank only!",
  },
  {
    id: "d3f9b7",
    name: "Splash",
    species: "aquatic",
    subcategory: "amphibian",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "smiling pink axolotl with feathery gills",
    description: "Axolotl with a permanent smile. Alien-cute and easier to care for than you'd think. Needs cold water.",
  },
  {
    id: "e7a2c8",
    name: "Dot",
    species: "aquatic",
    subcategory: "amphibian",
    specialNeeds: null,
    temperament: "shy",
    status: "available",
    prompt: "tiny african dwarf frog swimming",
    description: "Tiny African dwarf frog who hides in plants. Comes out at feeding time. Fully aquatic, easy keeper.",
  },
  {
    id: "f1b4d9",
    name: "Finn",
    species: "aquatic",
    subcategory: "fish",
    specialNeeds: null,
    temperament: "calm",
    status: "available",
    prompt: "royal blue betta fish with shimmering scales",
    description: "Royal blue betta who builds bubble nests. Looking for a quiet corner spot. Stunning colors!",
  },
];

// Map temperament to expression for image prompt
export const temperamentToExpression = {
  calm: "peaceful",
  playful: "happy",
  affectionate: "friendly",
  shy: "gentle",
  energetic: "excited",
  independent: "confident",
};
